# Generated by Django 4.2.10 on 2024-03-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FTRApp", "0002_vectorhandoverform"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machineType", models.CharField(max_length=50)),
                ("itemNum", models.CharField(max_length=50)),
                ("serialNum", models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name="vectorhandoverform", old_name="itemNum", new_name="city",
        ),
        migrations.RenameField(
            model_name="vectorhandoverform", old_name="serialNum", new_name="country",
        ),
        migrations.AddField(
            model_name="vectorhandoverform",
            name="coordname",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vectorhandoverform",
            name="farm",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vectorhandoverform",
            name="first",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vectorhandoverform",
            name="installco",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vectorhandoverform",
            name="last",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vectorhandoverform",
            name="lelyarea",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vectorhandoverform",
            name="lelyname",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vectorhandoverform",
            name="lelynum",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vectorhandoverform",
            name="machineDate",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vectorhandoverform",
            name="machineItemNo",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vectorhandoverform",
            name="machineSerialNo",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vectorhandoverform",
            name="num",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vectorhandoverform",
            name="street",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vectorhandoverform",
            name="zip",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vectorhandoverform",
            name="machineType",
            field=models.JSONField(),
        ),
    ]
