# Generated by Django 4.2.10 on 2024-03-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FTRApp", "0003_testform_rename_itemnum_vectorhandoverform_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm", models.CharField(max_length=50)),
                ("first", models.CharField(max_length=50)),
                ("last", models.CharField(max_length=50)),
                ("num", models.CharField(max_length=50)),
                ("street", models.CharField(max_length=50)),
                ("zip", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("lelynum", models.CharField(max_length=50)),
                ("lelyname", models.CharField(max_length=50)),
                ("lelyarea", models.CharField(max_length=50)),
                ("coordname", models.CharField(max_length=50)),
                ("installco", models.CharField(max_length=50)),
                ("machineType", models.JSONField()),
                ("machineDate", models.JSONField()),
                ("machineItemNo", models.JSONField()),
                ("machineSerialNo", models.JSONField()),
            ],
        ),
        migrations.DeleteModel(name="VectorHandoverForm",),
    ]
