# Generated by Django 4.2.10 on 2024-03-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FTRApp", "0004_vectorform_delete_vectorhandoverform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vectorform",
            name="machineDate",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vectorform",
            name="machineItemNo",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vectorform",
            name="machineSerialNo",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vectorform",
            name="machineType",
            field=models.CharField(max_length=50),
        ),
    ]
