# Generated by Django 4.2.10 on 2024-04-02 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FTRApp", "0006_lelycenterinfo_remove_user_name_user_city_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="UserInfo",),
    ]
