# Generated by Django 4.2.10 on 2024-04-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FTRApp", "0008_alter_machineinfo_vectorform"),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selection", models.CharField(default="", max_length=10)),
                ("remark", models.TextField(default="")),
            ],
        ),
        migrations.AddField(
            model_name="vectorformcompact",
            name="remark",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="vectorformcompact",
            name="selection",
            field=models.CharField(default="", max_length=10),
        ),
    ]
