# Generated by Django 4.2.10 on 2024-04-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FTRApp", "0010_alter_vectorformcompact_selection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vectorformcompact",
            name="selection",
            field=models.CharField(default="", max_length=100),
        ),
    ]
