# Generated by Django 4.2.10 on 2024-04-17 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FTRApp", "0012_form_machineinfogeneric_checklistitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm", models.CharField(default="", max_length=50)),
                ("first", models.CharField(default="", max_length=50)),
                ("last", models.CharField(default="", max_length=50)),
                ("num", models.CharField(default="", max_length=50)),
                ("street", models.CharField(default="", max_length=50)),
                ("zip", models.CharField(default="", max_length=50)),
                ("city", models.CharField(default="", max_length=50)),
                ("country", models.CharField(default="", max_length=50)),
                ("installations", models.TextField(default="0,0,0")),
                ("forms", models.TextField(default="")),
            ],
            options={"unique_together": {("last", "num")},},
        ),
        migrations.AlterField(
            model_name="form",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="FTRApp.customerinfo"
            ),
        ),
    ]
