# Generated by Django 4.2.10 on 2024-05-07 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("FTRApp", "0013_customerinfo_alter_form_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Form2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="checklistitem",
            name="itemNumber",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="form",
            name="type",
            field=models.CharField(
                choices=[
                    ("1", "VectorForm"),
                    ("2", "AstronautForm"),
                    ("3", "HorizonForm"),
                ],
                default="1",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "column_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("select", "Select"),
                            ("radio", "Radio"),
                        ],
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=list)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="FTRApp.form2",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Form2Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_last_name", models.CharField(max_length=100)),
                ("customer_number", models.CharField(max_length=100)),
                ("data", models.JSONField()),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form2_data",
                        to="FTRApp.form2",
                    ),
                ),
            ],
            options={
                "unique_together": {("form", "customer_last_name", "customer_number")},
            },
        ),
    ]
