# Generated by Django 4.2.10 on 2024-05-08 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "FTRApp",
            "0014_form2_alter_checklistitem_itemnumber_alter_form_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="lelyCenter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="FTRApp.lelycenterinfo"
            ),
        ),
        migrations.AlterField(
            model_name="form",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="FTRApp.customerinfo"
            ),
        ),
    ]
