# Generated by Django 5.0.4 on 2024-05-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTRApp', '0015_alter_form_lelycenter_alter_form_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='remaining1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='remaining2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='remaining3',
            field=models.IntegerField(default=0),
        ),
    ]
