# Generated by Django 4.2.10 on 2024-05-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FTRApp", "0018_alter_customerinfo_remaining1_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="machineinfo", name="vectorForm",),
        migrations.DeleteModel(name="TestForm",),
        migrations.DeleteModel(name="VectorChecklist",),
        migrations.DeleteModel(name="VectorForm",),
        migrations.RemoveField(model_name="vectorformcompact", name="lelyCenter",),
        migrations.RemoveField(model_name="vectorformcompact", name="user",),
        migrations.DeleteModel(name="MachineInfo",),
        migrations.DeleteModel(name="UserInfo",),
        migrations.DeleteModel(name="VectorFormCompact",),
    ]
